/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSavedIndexRouteImport } from './routes/dashboard/saved/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardSavedIdRouteImport } from './routes/dashboard/saved/$id'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard/admin/settings'
import { Route as DashboardAdminInvitationsRouteImport } from './routes/dashboard/admin/invitations'
import { Route as DashboardAdminCostTrackingRouteImport } from './routes/dashboard/admin/cost-tracking'
import { Route as DashboardAdminContentModerationRouteImport } from './routes/dashboard/admin/content-moderation'
import { Route as DashboardAdminUsersUserIdRouteImport } from './routes/dashboard/admin/users.$userId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedIndexRoute = DashboardSavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedIdRoute = DashboardSavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminInvitationsRoute =
  DashboardAdminInvitationsRouteImport.update({
    id: '/admin/invitations',
    path: '/admin/invitations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminCostTrackingRoute =
  DashboardAdminCostTrackingRouteImport.update({
    id: '/admin/cost-tracking',
    path: '/admin/cost-tracking',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminContentModerationRoute =
  DashboardAdminContentModerationRouteImport.update({
    id: '/admin/content-moderation',
    path: '/admin/content-moderation',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersUserIdRoute =
  DashboardAdminUsersUserIdRouteImport.update({
    id: '/admin/users/$userId',
    path: '/admin/users/$userId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/content-moderation': typeof DashboardAdminContentModerationRoute
  '/dashboard/admin/cost-tracking': typeof DashboardAdminCostTrackingRoute
  '/dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/saved/$id': typeof DashboardSavedIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/saved/': typeof DashboardSavedIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/content-moderation': typeof DashboardAdminContentModerationRoute
  '/dashboard/admin/cost-tracking': typeof DashboardAdminCostTrackingRoute
  '/dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/saved/$id': typeof DashboardSavedIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/saved': typeof DashboardSavedIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/content-moderation': typeof DashboardAdminContentModerationRoute
  '/dashboard/admin/cost-tracking': typeof DashboardAdminCostTrackingRoute
  '/dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/saved/$id': typeof DashboardSavedIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/saved/': typeof DashboardSavedIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/'
    | '/dashboard/admin/content-moderation'
    | '/dashboard/admin/cost-tracking'
    | '/dashboard/admin/invitations'
    | '/dashboard/admin/settings'
    | '/dashboard/saved/$id'
    | '/dashboard/admin/'
    | '/dashboard/saved/'
    | '/dashboard/settings/'
    | '/dashboard/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/dashboard/admin/content-moderation'
    | '/dashboard/admin/cost-tracking'
    | '/dashboard/admin/invitations'
    | '/dashboard/admin/settings'
    | '/dashboard/saved/$id'
    | '/dashboard/admin'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/dashboard/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/dashboard/'
    | '/dashboard/admin/content-moderation'
    | '/dashboard/admin/cost-tracking'
    | '/dashboard/admin/invitations'
    | '/dashboard/admin/settings'
    | '/dashboard/saved/$id'
    | '/dashboard/admin/'
    | '/dashboard/saved/'
    | '/dashboard/settings/'
    | '/dashboard/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved/': {
      id: '/dashboard/saved/'
      path: '/saved'
      fullPath: '/dashboard/saved/'
      preLoaderRoute: typeof DashboardSavedIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved/$id': {
      id: '/dashboard/saved/$id'
      path: '/saved/$id'
      fullPath: '/dashboard/saved/$id'
      preLoaderRoute: typeof DashboardSavedIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/invitations': {
      id: '/dashboard/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/dashboard/admin/invitations'
      preLoaderRoute: typeof DashboardAdminInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/cost-tracking': {
      id: '/dashboard/admin/cost-tracking'
      path: '/admin/cost-tracking'
      fullPath: '/dashboard/admin/cost-tracking'
      preLoaderRoute: typeof DashboardAdminCostTrackingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/content-moderation': {
      id: '/dashboard/admin/content-moderation'
      path: '/admin/content-moderation'
      fullPath: '/dashboard/admin/content-moderation'
      preLoaderRoute: typeof DashboardAdminContentModerationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users/$userId': {
      id: '/dashboard/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/dashboard/admin/users/$userId'
      preLoaderRoute: typeof DashboardAdminUsersUserIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminContentModerationRoute: typeof DashboardAdminContentModerationRoute
  DashboardAdminCostTrackingRoute: typeof DashboardAdminCostTrackingRoute
  DashboardAdminInvitationsRoute: typeof DashboardAdminInvitationsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardSavedIdRoute: typeof DashboardSavedIdRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardSavedIndexRoute: typeof DashboardSavedIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardAdminUsersUserIdRoute: typeof DashboardAdminUsersUserIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminContentModerationRoute: DashboardAdminContentModerationRoute,
  DashboardAdminCostTrackingRoute: DashboardAdminCostTrackingRoute,
  DashboardAdminInvitationsRoute: DashboardAdminInvitationsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardSavedIdRoute: DashboardSavedIdRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardSavedIndexRoute: DashboardSavedIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardAdminUsersUserIdRoute: DashboardAdminUsersUserIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
